### ISSUE TITLE
Memory leak after exiting view controller

### ISSUE THREAD

**Issue by digitalartworks** [bahlo/SwiftGif#21] opened 2016-02-10 16:25 UTC
Oh, sorry, I just confound Your lib with another :) Anyway I was using Your lib, but it is memory inefficient. Better way is to allocate i.e. 5 frames in memory as cache and prepare another in runtime.

Good luck!

**Comment by bahlo** [comment] 2016-02-10 16:27
Thank you for that information! :+1:

Maybe it would make sense to create a `destroy()`-Method to call on exit, I'll think check this.

**Comment by bahlo** [comment] 2016-04-04 21:48
Closed as duplicate of #6.

**Closed by bahlo** 2016-04-04 21:48 UTC
