### ISSUE TITLE
Compile Fail with Xcode 6.3 Final

### ISSUE THREAD

**Issue by kbirand** [bahlo/SwiftGif#3] opened 2015-04-14 10:40 UTC
let cfProperties = CGImageSourceCopyPropertiesAtIndex(source, index, nil)
is giving an error =
"Cannot invoke 'CGImageSourceCopyPropertiesAtIndex' with an argument list of type 'CGImageSourceRef,Uint,nil)'

**Comment by bahlo** [comment] 2015-04-14 10:57
Hey @kbirand, thanks for pointing out. I will look into this tonight.

**Comment by kbirand** [comment] 2015-04-15 21:14
No problem

**Comment by gaiabeatrice** [comment] 2015-04-16 10:15
The problem is that in
 let cfProperties = CGImageSourceCopyPropertiesAtIndex(source, index, nil) 
the index type is UInt but the index that we use is an Int type

**Comment by bahlo** [comment] 2015-04-16 18:08
Hey @gaiabeatrice, thanks for the hint. Unfortunately I haven't had the time yet to look into this.

It'd be great if you created a PR. :)

**Comment by JoelSimonoff** [comment] 2015-04-19 03:17
I am having the same Issue I fixed it, I didn't see any new PR so I will create one

**Comment by bahlo** [comment] 2015-04-23 12:18
Fixed in [`1.3.1`](https://github.com/bahlo/SwiftGif/releases/tag/v1.3.1).

**Closed by bahlo** 2015-04-23 12:18 UTC
